### ISSUE TITLE
bin/... is copied into site-packages/

### ISSUE THREAD

**Issue by mhsieh** [PacificBiosciences/kineticsTools#18]
1. is copyIpdSummaryDataset.py or writeSummaryToCmp ever used?
2. if not get rid of it from the package

**Comment by afif-elghraoui** [comment]
This issue was also reported against the Debian package (https://bugs.debian.org/831218). The files in bin don't seem to be necessary. The package builds fine and all tests (for which there is data available to run) pass without it on the Debian build servers and CI.

**Comment by natechols** [comment]
Fixed by #36.  I left the bin/ directory in the repo alone in case we want to update and use these in the future, but it isn't being installed any more.
