### ISSUE TITLE
8-bit or 16-bit IPD encoding?

### ISSUE THREAD

**Issue by dbrowneup** [PacificBiosciences/kineticsTools#50]
Hi, I'm converting some legacy bax.h5 files to the preferred BAM format via bax2bam. There is an option for bax2bam called --losslessframes:

```
    --losslessframes    Store full, 16-bit IPD/PulseWidth data, instead of
                        (default) downsampled, 8-bit encoding.
```

As it stands, I did not include this option, and so presumably my BAM files have the 8-bit encoding. I am wondering if this will affect any downstream analysis that I do with ipdSummary?

Thanks!

**Comment by natechols** [comment]
No, I don't have the results on hand right now, but we tested this back when we switched to BAM in 2015 (using a selection of microbial datasets using P6-C4 chemistry), and it didn't appear to matter which encoding was used.
