### ISSUE TITLE
the default value of the argument "maxCoverage"

### ISSUE THREAD

**Issue by PengNi** [PacificBiosciences/kineticsTools#51]
Hi all, I was wondering if the default value of the argument "maxCoverage" in [ipdSummary.py line 285](https://github.com/PacificBiosciences/kineticsTools/blob/master/kineticsTools/ipdSummary.py)  is set properly?

The default value of "maxCoverage" is set to be -1.

```
self.parser.add_argument('--maxCoverage',
                                 dest='maxCoverage',
                                 type=int, default=-1,
                                 help='Maximum coverage to use at each site')
```

However, if this argument is set to -1 by default, in the following codes in [KineticWorker.py line 501](https://github.com/PacificBiosciences/kineticsTools/blob/master/kineticsTools/KineticWorker.py),

```
        # If the user has specified a maximum coverage level to use, enforce it here -- just take the first n reads
        if self.options.maxCoverage is not None:
            maxCov = self.options.maxCoverage
            for x in views:
                d = x['data']
                d = d[0:maxCov]
                x['data'] = d
```

the _d = d[0:maxCov]_ which becomes _d=d[0:-1]_, will not assign all _n_ values in d but only the first _n-1_ values.

So Is it reasonable?

**Comment by PengNi** [comment]
Can somebody help? @nlhepler @dalexander @natechols

**Comment by nlhepler** [comment]
Hi @PengNi,

You appear to have uncovered a bug! Indeed, we would be losing a single read of coverage using the default values, which I am sure is unintended.

I will draft a patch to fix this, in the meantime please understand that the loss of a single read is unlikely to have a dramatic effect on the outcome.

**Comment by PengNi** [comment]
@nlhepler Thanks, got that.
