### ISSUE TITLE
Calculating Methylated Fraction

### ISSUE THREAD

**Issue by clarepacini** [PacificBiosciences/kineticsTools#54]
Hi,

I was hoping there may be a publication or white paper that explains how the methylated fraction is calculated, specifically for m6A? 

Thanks

**Comment by obanerjee** [comment]
[methylated_fraction_description.pdf](https://github.com/PacificBiosciences/kineticsTools/files/1741474/methylated_fraction_description.pdf)

Here is an informal document that I had written for myself.   There may also be a brief description contained in one or two publications by outside groups.

**Comment by clarepacini** [comment]
That's helpful, thanks!
