### ISSUE TITLE
Detecting something different from 4mC, 5mC and 6mA

### ISSUE THREAD

**Issue by OnlyHigh** [PacificBiosciences/kineticsTools#59]
Hi, 
I'm writing this issue to ask if kineticTools is capable to identify/assign identitiy to something different than 4mC, 5mC and 6mA. 

In case of possible, how could be done? 
Thanks in advance, 
Luis Alfonso.

**Comment by rhallPB** [comment]
Not without training your own discriminator. While other modifications are detected, i.e. there is a signal, it's not possible to identify the specific signal of anything other than 4mC and 6mA.

**Comment by rhallPB** [comment]
This would require someone with a signal processing / machine learning background, and the sequencing of a large set of training data, with known validated modifications. i.e. this isn't a simple or inexpensive experiment.

**Comment by OnlyHigh** [comment]
Thanks for the answer.
