### ISSUE TITLE
ipdsummary for target regions

### ISSUE THREAD

**Issue by guleiathms** [PacificBiosciences/kineticsTools#7]
I found ipdsummary is very slow in some part of chromosomes in hg19. So I don't want to run the ipdsummary for the whole chromosome. 
I wonder that is there a way that ipdsummary only does the calculations in the regions I specified?
Thanks.

**Comment by rhallPB** [comment]
I have not tested this approach, but it should be possible to sub-sample the cmp.h5 alignment file before running ipdsummary. cmph5tools in the pbh5tools package has a very flexible interface that allows sub-sampling the cmp.h5 by many metrics.
https://github.com/PacificBiosciences/pbh5tools/blob/master/doc/examples.md

**Comment by guleiathms** [comment]
Yes, I tested this approach. I selected data only mapped to a certain region. But when you run the ipdsummary, it still go through the whole chromosome. And the most time consuming part is not the calculations on the selected region, but rather on some other regions in the chromosome. So only retrieving data from cmp.h5 is not enough to speed up the analysis. It might be better to have an option in ipdsummary that allow us to specify regions rather than always going through the entire chromosome even there is no reads mapped on.

**Comment by mseetin** [comment]
Have you tried creating a new reference from a fasta file that only has the regions of the chromosome you care about and using that as the reference to which your reads get mapped?

**Comment by guleiathms** [comment]
Yes, I also thought about that. But if there are many regions, I think it is not a very convenient way.

**Comment by mseetin** [comment]
This tool was developed with an eye towards detecting modifications across a whole genome based on analyzing whole genome data.  I don't think there's a way to limit the scope of the mapping to a reference genome without creating a new reference that contains only the region you wish to map to, or at least some smaller continuous subregion of the chromosome that includes all of your regions of interest.

**Comment by guleiathms** [comment]
OK, let's try to create a new ref. And then I will need to extract the mapped reads from the sorted cmp.h5 and find them in many raw bas.h5 files. Then map them to the new ref. 
Could you please tell me which unique id that connect the reads between sorted cmp.h5 and bas.h5 files?
Thanks.

**Comment by dalexander** [comment]
Hi, I will soon be adding the capability to choose an analysis window, because we need to do such analyses as well.  I do not recommend cmph5tools here as it is slow.  I don't recommend the alternative mapping approaches either.

**Comment by dalexander** [comment]
Hi, I pushed the changes needed for this.  You can run on windows via  ``ipdSummary.py -wchr1:1000-2000,chr2:5000-6000``, etc.
