### ISSUE TITLE
build failure: pbcommand no longer offers pbparser_runner

### ISSUE THREAD

**Issue by smoe** [PacificBiosciences/kineticsTools#72]
Hello,
The pbparser_runner is imported in three different files (see https://github.com/PacificBiosciences/kineticsTools/search?q=pbparser&unscoped_q=pbparser) but no longer offered by https://github.com/PacificBiosciences/pbcommand. That changed API together with the pb* packages not offering releases makes it all a bit difficult to install the right thing and affects the Debian package that I was about to update.
Are there suggestions on what to do? I added a comment on a somewhat related issue https://github.com/PacificBiosciences/pbcommand/issues/190, you may have better ideas how to word that or whom to address.
Many thanks!
Steffen

**Comment by natechols** [comment]
Looks like the GitHub versions of our repos are out of sync - the tool contract/pbsmrtpipe support has been removed from pbcommand and everything has been ported to Python 3.  I'll see if I can get this repo updated to the current code.

**Comment by natechols** [comment]
The current version has been pushed to the repo, hopefully this resolves the problem.
