### ISSUE TITLE
what's the meaning of methylation fraction = 0

### ISSUE THREAD

**Issue by guleiathms** [PacificBiosciences/kineticsTools#8]
A quick question: I noticed that there are As identified as 6mA by ipdSummary.py, but the methylation fraction is 0. How is that possible? If the methylation level is 0, this A is not methylated, right?

Here are some examples: (the coverage and identificationQv are not too bad)
chr10	kinModCall	m6A	57690025	57690025	26	+	.	coverage=70;context=ACCCACCCCTAAAAAGAAGAAAAAGAAAAAAATGAAAAAGA;IPDRatio=1.80;frac=0.000;fracLow=0.000;fracUp=0.000;identificationQv=29
chr10	kinModCall	m6A	71760109	71760109	24	-	.	coverage=767;context=ATACCTAATAAAAAATGGAAAAAAAAAAAAAAAAGAGAAAA;IPDRatio=1.29;frac=0.000;fracLow=0.000;fracUp=0.000;identificationQv=35
chr11	kinModCall	m6A	3051998	3051998	34	+	.	coverage=84;context=AGACTAGCACCGGGCTAGGCATGCCAGACTAGCACCGGGCT;IPDRatio=2.05;frac=0.000;fracLow=0.000;fracUp=0.000;identificationQv=27
chr11	kinModCall	m6A	3052073	3052073	37	+	.	coverage=105;context=AGACTAGCACCGGGCTAGGCATGCCAGACTAGCACCGGGCT;IPDRatio=1.60;frac=0.000;fracLow=0.000;fracUp=0.000;identificationQv=19

**Comment by dalexander** [comment]
what was the command line that you ran?

**Comment by guleiathms** [comment]
ipdSummary.py --methylFraction --identify m6A,m4C -v --numWorkers 6 --outfile ${output} --reference ${ref} input.cmp.h5

**Comment by dalexander** [comment]
Interesting.  Would you be able to share data files with us so we can debug?  I can share FTP login details in email.

**Comment by guleiathms** [comment]
sure

**Comment by mhsieh** [comment]
closed due to lack of activity, please reopen it if you guys are still working on it.

**Comment by ZJkerry** [comment]
请问这个数据怎么看
